spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/api/v1
        - id: exchanger-service
          uri: http://localhost:8085
          predicates:
            - Path=/exchangers/**
          filters:
            - PrefixPath=/api/v1
        - id: feedback-service
          uri: http://localhost:8085
          predicates:
            - Path=/feedbacks/**
          filters:
            - PrefixPath=/api/v1
        - id: goal-service
          uri: http://localhost:8085
          predicates:
            - Path=/goals/**
          filters:
            - PrefixPath=/api/v1
        - id: pricing-service
          uri: http://localhost:8082
          predicates:
            - Path=/crypto-pricing
